server:
  port: 8001
  servlet:
    context-path: /member

#  logging.level.com.jiawa.train.member.mapper=trace
# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://rm-2zeem9cul93l70ieleo.mysql.rds.aliyuncs.com:3306/train_member?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_member
    password: WZG7014nbilove
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis xml路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml


logging:
  level:
    com.wzg.train.member.mapper: TRACE
