POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###

GET http://localhost:8000/member/passenger/query-list?page=1&size=3
Accept: application/json
token: {{token}}

###

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1938494887704006656,
  "memberId": 1936956971949363200,
  "name": "wzgnb",
  "idCard": "12334198921",
  "type": "1"
}

###

DELETE http://localhost:8000/member/passenger/delete/1938494887704006656
Accept: application/json
token: {{token}}

###