server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/member/**
        - id: business
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/business/**
        - id: batch
          uri: http://127.0.0.1:8003
          predicates:
            - Path=/batch/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true
            maxAge: 3600
  devtools:
    livereload:
      port: 35730