server:
  port: 8002
  servlet:
    context-path: /business

#  logging.level.com.wzg.train.member.mapper=trace
# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://rm-2zeem9cul93l70ieleo.mysql.rds.aliyuncs.com:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_business
    password: WZG7014nbilove
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: business
  data:
    redis:
      host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
      port: 6379
      password: Redis000
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      cache-null-values: true
      time-to-live: 60s

  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:18080

# mybatis xml路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  # 配置为statement，即关闭一级缓存
  configuration:
    local-cache-scope: statement


logging:
  level:
    com.wzg.train.business.mapper: TRACE