server:
  port: 8003
  servlet:
    context-path: /batch

#  logging.level.com.wzg.train.batch.mapper=trace
# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://rm-2zeem9cul93l70ieleo.mysql.rds.aliyuncs.com:3306/train_batch?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_batch
    password: WZG7014nbilove
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis xml路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml


logging:
  level:
    com.wzg.train.batch.mapper: TRACE
